apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-staging-app
  namespace: argocd
spec:
  project: staging
  source:
    repoURL: https://github.com/elxandre/test-TRG.git
    targetRevision: HEAD
    path: k8s/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true